
import React from 'react';
import { 
  LayoutDashboard, 
  Users, 
  ShoppingBag, 
  Wallet, 
  Settings, 
  Plus,
  LogOut,
  Calendar,
  CheckCircle,
  AlertCircle,
  TrendingUp,
  Package,
  Search,
  ChevronRight,
  ChevronLeft,
  X,
  Edit2,
  Phone,
  MapPin,
  ChevronDown,
  ChevronUp,
  BarChart3,
  UserPlus,
  Briefcase,
  Trash2,
  Download,
  Upload,
  Database,
  Eye,
  EyeOff,
  Printer,
  RotateCcw,
  Camera,
  Share2,
  Banknote,
  History,
  FileText
} from 'lucide-react';

export const ICONS = {
  Dashboard: <LayoutDashboard size={24} />,
  Clients: <Users size={24} />,
  Sales: <ShoppingBag size={24} />,
  Payments: <Wallet size={24} />,
  Wallet: <Wallet size={24} />,
  Settings: <Settings size={24} />,
  Add: <Plus size={24} />,
  Logout: <LogOut size={20} />,
  Calendar: <Calendar size={18} />,
  Check: <CheckCircle size={18} />,
  Alert: <AlertCircle size={18} />,
  Trending: <TrendingUp size={24} />,
  Product: <Package size={24} />,
  Search: <Search size={20} />,
  Right: <ChevronRight size={20} />,
  Left: <ChevronLeft size={20} />,
  Down: <ChevronDown size={20} />,
  Up: <ChevronUp size={20} />,
  Close: <X size={24} />,
  Edit: <Edit2 size={16} />,
  Phone: <Phone size={16} />,
  Map: <MapPin size={16} />,
  Reports: <BarChart3 size={24} />,
  Sellers: <Briefcase size={24} />,
  UserPlus: <UserPlus size={20} />,
  Trash: <Trash2 size={16} />,
  Download: <Download size={20} />,
  Upload: <Upload size={20} />,
  Database: <Database size={24} />,
  Eye: <Eye size={20} />,
  EyeOff: <EyeOff size={20} />,
  Printer: <Printer size={16} />,
  Return: <RotateCcw size={16} />,
  Camera: <Camera size={20} />,
  Share: <Share2 size={20} />,
  Money: <Banknote size={20} />,
  History: <History size={20} />,
  FileText: <FileText size={16} />
};

export const ROUTES = {
  LOGIN: '/',
  REGISTER: '/register',
  SETUP: '/setup',
  DASHBOARD: '/dashboard',
  CLIENTS: '/clients',
  CLIENT_DETAILS: '/clients/:id',
  SALES: '/sales',
  PAYMENTS: '/payments',
  PRODUCTS: '/products',
  NEW_SALE: '/sales/new',
  SELLERS: '/sellers',
  SELLER_DETAILS: '/sellers/:id',
  REPORTS: '/reports',
  SETTINGS: '/settings'
};

export const COLORS = {
  primary: '#FF7A00',
  dark: '#2E2E2E',
  darker: '#1A1A1A',
  text: '#E5E5E5',
  success: '#10B981',
  danger: '#EF4444'
};
